---
- name: roles/postgresql/tasks/main.yml
  include_vars: vars/centos{{ ansible_distribution_major_version }}.yml

- name: Remove old postgresql data
  file: 
    path:   /var/lib/pgsql/data
    state:  absent
  become: yes

- name: Install PGDG repository
  yum: 
    name:   "{{ PG_REPO_URI }}"
  become: yes

- name: Install SCL(Software CoLlection) for LLVM
  yum:
    name:
      - centos-release-scl
  become: yes

- name: Install postgresql packages
  yum:
    name:
      - postgresql{{ PG_VERSION }}-server
      - postgresql{{ PG_VERSION }}-devel
      - php-pgsql
      - python-psycopg2
  become: yes
- name: Add {{ PG_BIN_DIR }} to $PATH
  template:
    src: pgsql.sh
    dest: /etc/profile.d
  become: yes
  tags: pg-package
- import_tasks: init.yml
  ignore_errors: yes
  tags: pg-init
