---
- name: roles/openldap/tasks/main.yml
  assert: { that: true, quiet: true }

- name: Install LDAP support packages
  yum: 
    name:
      - openldap-servers
      - openldap-clients
      - migrationtools
      - ldapvi
  become: yes

- name: Start slapd
  systemd:
    name: slapd
    state: started
    enabled: true
  become: true

- name: Create directory for remote_tmp
  file:
    path: /var/lib/ldap/.ansible/tmp
    owner: ldap
    group: ldap
    mode: 0700
    recurse: true
  become: true

- name: Set DB_CONFIG
  copy:
    src: /usr/share/openldap-servers/DB_CONFIG.example
    dest: /var/lib/ldap/DB_CONFIG
    remote_src: true
  become: yes
  become_user: ldap

- name: Prepare work directory
  file:
    path: "{{ LDAP_WORKDIR }}"
    state: directory

- name: Check olcSuffix
  community.general.ldap_search:
    dn: olcDatabase={2}hdb,cn=config
    bind_dn: cn=config
    bind_pw: "{{ LDAP_BINDPW }}"
    attrs: [ 'olcSuffix' ]
  register: hdb
  tags: dump
  ignore_errors: true

# ok: [localhost] => {
#     "hdb": {
#         "changed": false,
#         "failed": false,
#         "results": [
#             {
#                 "dn": "olcDatabase={2}hdb,cn=config",
#                 "olcSuffix": "dc=example,dc=com"
#             }
#         ]
#     }
# }

- debug:
#   var: hdb.results.olcSuffix            - variable is not defined
#   var: hdb.results['olcSuffix']         - variable is not defined
#   var: "{{ hdb.results['olcSuffix'] }}" - list object has no attribute 'olcSuffix'
#   msg: "{{ hdb.results | string | regex_search('olcSuffix') }}"   => olcSuffix
#   msg: "{{ hdb.results.'olcSuffix' }}"  - template error
    var: hdb
  tags: dump

- set_fact:
    init: true

- set_fact:
    init: false
  when:
    - not hdb.failed
    - hdb.results[0]['olcSuffix'] == LDAP_BASEDN
  tags: dump

- name: Open firewall
  firewalld:
    service: ldap
    immediate: true
    permanent: true
    state: enabled
  become: true

- import_tasks: instance.yml
  when: init
