---
- name: roles/xdebug/tasks/main.yml
  command: echo

- name: Install php-xdebug for remi
  yum: 
    enablerepo: "{{ PHP_ENABLEREPO }}"
    name: "{{ PHP_PKG_PREFIX }}-pecl-xdebug"
  become: yes
  when: PHP_ENABLEREPO is defined

- name: Put additional settings file.
  template:
    src:  16-xdebug.ini
    dest: "{{ PHP_INI_DIR }}/php.d/"
  become: yes
  notify: restart php-fpm

- name: |
    NOTE: Please change xdebug.remote_host value in {{ PHP_INI_DIR }}/php.d/16-xdebug.ini to the IP address of your machine runs xdebug/netbeans.
  command: echo
