---
- name: roles/laravel/tasks/core.yml
  command: echo

# - name: core-01.Check for existence of the laravel installer
#   stat: 
#     path: "{{ COMPOSER_GLOBAL_BIN }}/laravel"
#   register: laravel_installer

# - name: core-02.Install laravel installer
#   composer:
#     command: require
#     arguments: "laravel/installer{{ LARAVEL_INSTALLER_VER }}"
#     working_dir: "{{ COMPOSER_HOME }}"
#   environment:
#     PATH: "/usr/bin:{{ PHP_BIN_DIR }}:{{ COMPOSER_GLOBAL_BIN }}"

- name: core-01. Create laravel project
  composer:
    command: create-project
    prefer-dist: yes
    global_command: yes
    arguments: laravel/laravel {{ LARAVEL_HOME }} {{ LARAVEL_VERSION }}
  environment:
    PATH: "/usr/bin:{{ PHP_BIN_DIR }}:{{ COMPOSER_GLOBAL_BIN }}"

- name: core-03.Put laravel.conf for nginx
  template:
    src:  laravel.conf
    dest: /etc/nginx/conf.d/laravel.conf
    force: yes
  become: yes
  notify: reload nginx

- name: core-05.Install aws-sdk-php-laravel
  composer:
    command: require
    arguments: "aws/aws-sdk-php-laravel:~3.0"
    working_dir: "{{ LARAVEL_HOME }}"
  environment:
    PATH: "/usr/bin:{{ PHP_BIN_DIR }}:{{ COMPOSER_GLOBAL_BIN }}"

- name: core-06.Change owner under laravel
  file: 
    path:     "{{ LARAVEL_HOME }}" 
    state:    directory
    owner:    "{{ ansible_user_id }}"
    recurse:  yes
  become: yes

- name: core-07.Open permissions of storage/*
  file: 
    path:     "{{ LARAVEL_HOME }}/storage" 
    state:    directory
    mode:     "a+w" 
    recurse:  yes
  become: yes

- name: core-08.Open permissions of bootstrap/cache
  file: 
    path:     "{{ LARAVEL_HOME }}/bootstrap/cache"
    state:    directory
    mode:     "a+w" 
    recurse:  yes
  become: yes
  notify: restart php-fpm

- name: Put laravel.sh for adding PATH
  copy:
    src: laravel.sh
    dest: /etc/profile.d
  become: yes
