---
- name: roles/ldap/tasks/install.yml
  command: echo
- name: Install LDAP support packages
  yum: 
    name:
      - openldap-servers
      - openldap-clients
  become: yes

- name: create directory for remote_tmp
  file:
    path: /var/lib/ldap/.ansible/tmp
    state: directory
    mode: 0700
  become: yes

- name: Set DB_CONFIG
  copy:
    src: /usr/share/openldap-servers/DB_CONFIG.example
    dest: /var/lib/ldap/DB_CONFIG
    remote_src: true
  become: yes
  become_user: ldap
  notify: start slapd
