dependencies:
  - { role: php-fpm,    tags: before_laravel}
  - { role: composer,   tags: before_laravel}
  - { role: postgresql, tags: before_laravel, when: DB_TYPE == "pgsql" }
  - { role: mariadb,    tags: before_laravel, when: DB_TYPE == "mysql" }
