---
- name: roles/cakephp3/tasks/debug_kit.yml
  command: echo

- name: Set debug mode
  lineinfile:
    path: "{{ CAKE3_HOME }}/config/app.php"
    line: "    'debug' => true,"
    insertafter: "^    'debug' => filter_var"

- name: Comment out original debug entry
  replace:
    path: "{{ CAKE3_HOME }}/config/app.php"
    regexp: "^    ('debug' => filter_var)"
    replace:   '//  \1'

- name: Force enable DebugKit
  blockinfile:
    path: "{{ CAKE3_HOME }}/config/bootstrap.php"
    block: |
      if (Configure::read('debug')) {
          Configure::write('DebugKit', [ 'forceEnable' => true ]);
          Plugin::load('DebugKit', ['bootstrap' => true, 'routes' => true]);
      }

- name: Create symbolic links for plugins
  command: ./bin/cake plugin assets symlink
  args:
    chdir: "{{ CAKE3_HOME }}"
