---
- name: roles/wordpress/tasks/core.yml
  set_fact:
    WP_CLI: /usr/local/bin/wp

- name: Get wp-cli if not exists
  get_url:
    url: "{{ WP_CLI_ARCHIVE }}"
    dest: "{{ WP_CLI }}"
    mode: 0755
  become: yes

- name: Get WP_ARCHIVE_FILE if not already downloaded
  get_url:
    url: "{{ WP_ARCHIVE_URL }}"
    dest: /tmp/{{ WP_ARCHIVE_FILE }}

- name: Extract core archive
  unarchive:
    src: /tmp/{{ WP_ARCHIVE_FILE }}
    dest: "{{ WWW_BASE }}"
    remote_src: yes
  become: yes

- name: Create wp-config.php
  template:
    src: wp-config.php
    dest: "{{ WP_HOME }}"
  become: yes

- name: Remove previous database
  mysql_db:
    login_user: root
    name: "{{ WP_DB_NAME }}"
    state: absent
  when: WP_REMOVE_PREVIOUS_DB == true
  
- name: Create Database
  mysql_db:
    login_user: root
    name: "{{ WP_DB_NAME }}"
  
- name: Create Database User
  mysql_user:
    login_user: root
    name: "{{ WP_DB_USER }}"
    password: "{{ WP_DB_PASSWORD }}"
    login_host: "{{ WP_DB_HOST }}"
    priv: "{{ WP_DB_NAME }}.*:ALL,GRANT"
  
- name: Install wp instance --path={{ WP_HOME }}
  shell: "{{ WP_CLI }} core install --path={{ WP_HOME }}
    --url={{ WP_SERVER_NAME }} --title='{{ WP_TITLE }}' 
    --admin_user={{ WP_ADMIN_USER }} --admin_password={{ WP_ADMINPASS }} 
    --admin_email={{ WP_ADMIN_EMAIL }}"
  become: yes
  notify: reload php-fpm

- name: Put nginx config file
  template:
    src: wordpress.conf
    dest: /etc/nginx/conf.d
  become: yes
  notify: reload nginx

- name: Change owner and permission of the directory tree
  file:
    path: "{{ WP_HOME }}"
    owner: "{{ ansible_user_id }}"
    group: nginx
    mode: g+rw
    recurse: yes
    state: directory
  become: yes
