---
- name: roles/mariadb-php/tasks/main.yml
  command: echo

- name: Install mariadb bindings from remiXX
  yum:
    enablerepo: remi,remi-{{ PHP_REPO }}
    name: php-mysqlnd
  become: yes
  notify: reload php-fpm
