---
- name: ~/ansible-centos7/roles/pgpoolAdmin/tasks/main.yml
  command: echo

- name: Get source tree
  git:
    repo: https://github.com/pgpool/pgpooladmin.git
    dest: "{{ PPA_HOME }}"
  become: yes
  tags: pgpoolAdmin

- name: make templates_c directory
  file:
    path: "{{ PPA_HOME }}/templates_c"
    state: directory
    mode: 0777
  become: yes
  tags: pgpoolAdmin

- name: permit write access to config
  file:
    path: "{{ PPA_HOME }}/conf/pgmgt.conf.php"
    owner: "{{ WEBSERVER_USER }}"
    group: "{{ WEBSERVER_GROUP }}"
    mode: 0644
  become: yes
  tags: pgpoolAdmin

- name: Import vars involved with pgpool
  include_vars: '../../roles/pgpool/vars/main.yml'

# according to these playbooks, pgpool.conf is not yet created for now

- name: permit write access to configs for pgpool
  file:
    path: "{{ PGPOOL_CONF_DIR }}/{{ item }}"
    owner: "{{ WEBSERVER_USER }}"
    group: "{{ WEBSERVER_GROUP }}"
    mode: 0644
  with_items:
#   - pgpool.conf
    - pcp.conf
  become: yes
  tags: pgpoolAdmin

- name: overwrite defaultParameter.php
  template:
    src: defaultParameter.php
    dest: "{{ PPA_HOME }}/install/defaultParameter.php"
  become: yes
  tags: pgpoolAdmin

- name: deply config for nginx
  template:
    src: pgpoolAdmin.conf
    dest: /etc/nginx/conf.d/pgpoolAdmin.conf
    force: yes
  become: yes
  notify: reload nginx
  tags: pgpoolAdmin

