---
- name: roles/mariadb/tasks/main.yml
  command: echo

- name: Get MariaDB installation script
  get_url:
    url: https://downloads.mariadb.com/MariaDB/mariadb_repo_setup
    dest: "{{ ansible_user_dir }}"

- name: Run MariaDB installation script(install repository)
  command: sh {{ ansible_user_dir }}/mariadb_repo_setup \
    --mariadb-server-version=mariadb-{{ MARIADB_VER }}
  become: yes

- name: Install mariadb packages
  yum: 
    name:
      - mariadb-server
      - python2-PyMySQL
      - python-psycopg2
  become: yes

- name: Autostart mariadb 
  systemd: 
    name:     mariadb
    state:    started 
    enabled:  yes
  become: yes

- name: Set MariaDB's root password
  mysql_user:
    login_unix_socket:  "{{ MARIADB_SOCKET }}"
    name: root
    password: "{{ MARIADB_ROOT_PW }}"
  become: yes
  tags: set_password

- name: Customize /root/.my.cnf
  template:
    src: my.cnf
    dest: /root/.my.cnf
  become: yes

- name: Deploy customized server.cnf
  template:
    src: server.cnf
    dest: /etc/my.cnf.d/
  become: yes

- name: Restarting mariadb for applying changes
  systemd: 
    name:     mariadb
    state:    restarted 
    enabled:  yes
  become: yes

- name: Grant Access from development client
  firewalld:
    immediate: yes
    permanent: yes
    state: enabled
    rich_rule: 'rule family=ipv4 service name="mysql" source address="{{ item }}" accept'
  become: yes
  with_items: "{{ DB_DEV_CIDR }}"
  notify: restart firewalld
