---
- name: roles/mariadb/tasks/main.yml
  command: echo

- name: Install mariadb packages
  yum: 
    name:
      - mariadb-server
      - mariadb
      - mysql-connector-python
      - MySQL-python
  become: yes

- name: Install mariadb bindings from remi
  yum:
    enablerepo: remi,remi-php72
    name: "{{ PHP_PKG_PREFIX }}-mysqlnd"
  become: yes
  notify: reload php-fpm
  when: PHP_REPO == "remi72"

- name: Install mariadb bindings from webtatic
  yum:
    name: "{{ PHP_PKG_PREFIX }}-mysqlnd"
  become: yes
  notify: reload php-fpm
  when: PHP_REPO == "webtatic72"

# zoneinfo support - cf. https://github.com/mjanser/ansible-role-mysql
# If check_mode is "no", the command module runs as "normal mode" 
# even if ansible-playbook envoked with --check option.
# https://docs.ansible.com/ansible/2.5/user_guide/playbooks_checkmode.html

- name: Set encoding for server
  lineinfile:
    path: /etc/my.cnf.d/server.cnf
    line: character-set-server=utf8
    regexp: ^character-set-server=utf8
    insertafter: ^\[mysqld\]
  become: yes
  tags: mariadb

- name: Enable mariadb
  service: name=mariadb state=started enabled=yes
  become: yes

- name: Check zoneinfo presence
  command: mysql -NBe "SELECT COUNT(*) FROM mysql.time_zone"
  register: mysql_timezones_count
  changed_when: false
  check_mode: no
  become: yes

- name: ensure timezone data is imported
  shell: "mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql mysql"
  when: mysql_timezones_count.stdout|int < 1
  become: yes

- name: Create User
  mysql_user:
    name: "{{ ansible_user_id }}"
    password: ''
    priv: '*.*:ALL'
  become: yes
