# Default "composer" RPM package depends on php-5.4, so we install it 
# from the original site.
---
- name: roles/composer/tasks/main.yml
  command: echo

- name: get Composer installer
  get_url:
    url:  https://getcomposer.org/installer 
    dest: /tmp/composer-setup.php
  become: yes
  tags: composer

- name: Install composer
  command: /usr/bin/php /tmp/composer-setup.php --install-dir="/usr/bin"  \
    --filename="composer"
  become: yes
  tags: composer

- name: Prepare $COMPOSER_HOME directory
  file:
    path: "{{ COMPOSER_HOME }}"
    state: directory

- name: Add $COMPOSER_GLOBAL_BIN to $PATH
  template: 
    src: composer.sh 
    dest: /etc/profile.d/
  become: yes

- name: Use https://packagist.jp instead
  composer: 
    command: config
    arguments: -g repos.packagist composer https://packagist.jp
    working_dir: "{{ COMPOSER_HOME }}"
  tags: packagist

- name: Use prestissimo - composer parallel install plugin
  composer: 
    command: require
    arguments: hirak/prestissimo
    working_dir: "{{ COMPOSER_HOME }}"
  tags: packagist
