---
- name: roles/vnc/tasks/main.yml
  command: echo
- name: Install GNOME Desktop and VNC server
  yum: 
    name:
      - "@^gnome-desktop-environment"
      - tigervnc-server
  become: yes
- name: prepare the directory for vnc auth
  file:
    path: "{{ ansible_user_dir }}/.vnc"
    state: directory
- name: enable vnc access without a password
  shell: echo | vncpasswd -f > {{ ansible_user_dir }}/.vnc/passwd 
- name: Copy vnc.sh to /etc/profile.d
  copy:
    src: vnc.sh
    dest: /etc/profile.d
  become: yes
