---
- name: roles/pgpool/tasks/main.yml
  command: echo
  tags: pgpool

- name: Install pgpool-II packages
  yum:
    name:
      - pgpool-II-{{ PG_VERSION }}
      - pgpool-II-{{ PG_VERSION }}-extensions
      - ed
  become: yes
  tags: pgpool

- name: Prepare for pid directory
  file:
    path: /var/run/pgpool-II-{{ PG_VERSION }}/
    state: directory
    owner: postgres
    group: postgres
  become: yes

- name: Add {{ PGPOOL_BIN_DIR }} to $PATH
  template:
    src: pgpool.sh
    dest: /etc/profile.d
  become: yes

- import_tasks: pgpool_recovery.yml
  tags: pgpool

- import_tasks: config.yml
  tags: pgpool

- name: Start pgpool-II
  systemd:
    name: "{{ PGPOOL_SERVICE }}"
    state: started
  become: yes
