#!/bin/bash
#
if [ $# -eq 0 ]; then
  echo "Register a MFA user"
  echo
  echo "Usage: $0 username"
  echo "    usename ==> ^[A-Za-z][A-Za-z0-9-_]+"
  exit
fi
user=$1
id $user >& /dev/null 
if [ $? -eq 0 ]; then
  echo "User $user already exists."
  exit 1
fi
sudo useradd -g radius-enabled $user
yes | sudo -u $user /usr/local/bin/google-authenticator > /tmp/$user.log
head -3 /tmp/$user.log | tail -1
