# Dependencies for deleveping PHP Extentsions
---
- name: roles/php-ext/tasks/main.yml
  command: echo

- name: Install packages required for building php extension
  yum: 
    enablerepo: remi,remi-{{ PHP_REPO }
    name:
      - php-devel
      - php-devel
      - libxml2-devel
      - openssl-devel
      - readline-devel
      - autoconf
      - automake
      - re2c
      - yum-utils
      - rpm-build
  become: yes
