# roles/pgpool/vars/main.yml
PCP_USER:             "{{ ansible_user_id }}"
PCP_PASSWD_RAW:       '0123'
PGPOOL_RECOVERY:      "{{ PG_SHARE_DIR }}/extension/pgpool-recovery.sql"
PGPOOL_BIN_DIR:       /usr/pgpool-{{ PG_VERSION }}/bin
PGPOOL_LIB_DIR:       /usr/pgpool-{{ PG_VERSION }}/lib
PGPOOL_SHARE_DIR:     /usr/pgpool-{{ PG_VERSION }}/share
PGPOOL_CONF_DIR:      /etc/pgpool-II-{{ PG_VERSION }}
PGPOOL_RUNSTATE_DIR:  /var/run/pgpool-II-{{ PG_VERSION }}
PGPOOL_LOG_DIR:       /var/log/pgpool-II-{{ PG_VERSION }}
PGPOOL_SERVICE:       pgpool-II-{{ PG_VERSION }}
