# roles/pgpool/vars/main.yml
PCP_USER:             "{{ ansible_user_id }}"
PCP_PASSWD_RAW:       pcppass
PGPOOL_RECOVERY:      "{{ PG_SHARE_DIR }}/extension/pgpool-recovery.sql"
PGPOOL_BIN_DIR:       /usr/pgpool-10/bin
PGPOOL_LIB_DIR:       /usr/pgpool-10/lib
PGPOOL_SHARE_DIR:     /usr/pgpool-10/share
PGPOOL_CONF_DIR:      /etc/pgpool-II-10
PGPOOL_RUNSTATE_DIR:  /var/run/pgpool-II-10
PGPOOL_LOG_DIR:       /var/log/pgpool-II-10
