---
- name: roles/base/tasks/mandatory.yml
  command: echo
- name: Install tools required for CentOS 7.x
  yum: 
    name:
      - chrony
      - glibc-devel
      - gcc-c++
      - python-passlib
      - git
      - elinks
      - patch
      - rsync
      - vim-enhanced
      - nkf
      - bind-utils
      - unzip
      - bzip2
      - wget
      - w3m
      - python2-pip
      - kernel-devel
      - man
      - npm
  become: yes
  when: ansible_distribution_major_version == '7'

- name: Install tools required for CentOS 6.x
  yum:
    name:
      - chrony
      - glibc-devel
      - gcc-c++
      - python-passlib
      - git
      - elinks
      - patch
      - rsync
      - vim-enhanced
      - nkf
      - bind-utils
      - unzip
      - bzip2
      - wget
      - w3m
      - python-pip
      - libselinux-python
      - kernel-devel
      - man
      - npm
  become: yes
  when: ansible_distribution_major_version == '6'

- name: Upgrade pip
  pip:
    name: pip
    state: latest
  become: yes

- name: yum update
  yum:
    name: '*'
    state: latest
  become: yes

- name: Prepare directory for WWW_BASE
  file:
    path:     "{{ WWW_BASE }}"
    state:    directory
    owner:    "{{ ansible_user_id }}"
  become: yes

- name: Set default language for python
  copy:
    src: sitecustomize.py
    dest: /usr/lib64/python2.7/
  become: yes
