---
- name: roles/base/tasks/phprepo.yml
  command: echo

- name: Validate PHP_REPO variable
  command: echo
  failed_when:
    - PHP_REPO != 'remi56'
    - PHP_REPO != 'remi72'
    - PHP_REPO != 'remi73'
    - PHP_REPO != 'remi74'

- name: set vars for php repositories
  include_vars: "{{ PHP_REPO }}.yml"

# - name: Check for access to the Internet
#   wait_for: host=www.yahoo.co.jp port=80 timeout=5

- name: Check existence of RPM-GPG-KEY-EPEL-{{ _V }}
  stat:
    path: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ _V }}
  register: epel_key

- name: Install remi repositories
  yum:
    name: "{{ PHP_REPO_PKG }}"
  become: yes
  when: PHP_REPO in [ 'remi56', 'remi72', 'remi73', 'remi74' ]

- name: Disable remi-php*
  command: yum-config-manager --disable remi-php*
  become: yes

- name: Enable {{ PHP_REPO_PKG }}
  command: yum-config-manager --enable {{ PHP_ENABLEREPO }}
  become: yes
