---
- name: roles/base/tasks/phprepo.yml
  command: echo

- name: Validate PHP_REPO variable
  command: echo
  failed_when: PHP_REPO is not regex("remi(56|7[234])")

# - name: Check for access to the Internet
#   wait_for: host=www.yahoo.co.jp port=80 timeout=5

- name: Check existence of RPM-GPG-KEY-EPEL-{{ _V }}
  stat:
    path: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ _V }}
  register: epel_key

- name: Install remi repositories
  yum:
    name: "{{ REMI_RELEASE }}"
  become: yes

- name: Disable remi-php*
  command: yum-config-manager --disable remi-php*
  become: yes

- name: set PHP_ENABLEREPO for remi56
  set_fact:
    PHP_ENABLEREPO: remi-php56
  when: PHP_REPO == "remi56"

- name: set PHP_ENABLEREPO for remi72
  set_fact:
    PHP_ENABLEREPO: remi-php72
  when: PHP_REPO == "remi72"

- name: set PHP_ENABLEREPO for remi73
  set_fact:
    PHP_ENABLEREPO: remi-php73
  when: PHP_REPO == "remi73"

- name: set PHP_ENABLEREPO for remi74
  set_fact:
    PHP_ENABLEREPO: remi-php74
  when: PHP_REPO == "remi74"
  tags: remi

- name: Enable {{ PHP_REPO_PKG }}
  command: yum-config-manager --enable {{ PHP_ENABLEREPO }}
  become: yes
  tags: remi
