---
- name: roles/php/tasks/phprepo.yml
  command: echo

- name: Validate PHP_REPO variable
  command: echo
  failed_when: PHP_REPO is not regex("remi(56|7[234])")

- name: Install remi repositories
  yum:
    name: "{{ REMI_RELEASE }}"
  become: yes

- name: Disable remi-php*
  command: yum-config-manager --disable remi-php*
  become: yes

- name: Determine PHP_ENABLEREPO
  set_fact:
    PHP_ENABLEREPO: remi-php{{ PHP_REPO | regex_replace('remi', '') }}
  tags: remi

- name: Enable {{ PHP_ENABLEREPO }}
  command: yum-config-manager --enable {{ PHP_ENABLEREPO }}
  become: yes
  tags: remi
