---
- name: roles/zabbix/tasks/main.yml
  command: echo

- name: Install zabbix repo
  yum:
    name: https://repo.zabbix.com/zabbix/4.2/rhel/7/x86_64/zabbix-release-4.2-2.el7.noarch.rpm
  become: yes

- name: Install zabbix and dependencies
  yum:
    name: 
      - zabbix-server-pgsql
      - zabbix-web-japanese
  become: yes

- name: Create DB User for zabbix
  postgresql_user:
    name: "{{ ZABBIX_DB_USERNAME }}"
    password: "{{ ZABBIX_DB_PASSWORD }}"
    role_attr_flags: NOSUPERUSER

- name: Create home directory for DB user
  file:
    path: /var/lib/{{ ZABBIX_DB_USERNAME }}
    state: directory
    owner: "{{ ZABBIX_DB_USERNAME }}"
  become: yes

- name: Check if Database exists
  command: psql {{ ZABBIX_DB_DATABSE }}
  register: db
  ignore_errors: yes

# - debug: var=db

- name: Create Database for zabbix
  postgresql_db:
    name: "{{ ZABBIX_DB_DATABSE }}"
    owner: "{{ ZABBIX_DB_USERNAME }}"
  when: ! db.rc

- set_fact:
    SCHEMA: /usr/share/doc/zabbix-server-pgsql-{{ ZABBIX_VER }}/create.sql.gz

- name: Import schema and data
  shell: zcat {{ SCHEMA }} | psql {{ ZABBIX_DB_DATABSE }}
  when: ! db.rc

- name: Change owner of database objects
  postgresql_owner:
    db: "{{ ZABBIX_DB_DATABSE }}"
    new_owner: "{{ ZABBIX_DB_USERNAME }}"
    reassign_owned_by: "{{ ansible_user_id }}"

# TODO: TimescaleDB support

- name: Set DBPassword in zabbix_server.conf
  lineinfile:
    path: /etc/zabbix/zabbix_server.conf
    regexp: ^DBPassword=
    line: "DBPassword={{ ZABBIX_DB_PASSWORD }}"
    insertafter: DBPassword=
  become: yes

- name: Set DBPort in zabbix_server.conf
  lineinfile:
    path: /etc/zabbix/zabbix_server.conf
    regexp: ^DBPort=
    line: "DBPort={{ ZABBIX_DB_PORT }}"
    insertafter: DBPort=
  become: yes

- name: Change group for php directory
  file:
    path: /var/lib/php/session
    state: directory
    group: apache
  become: yes

- name: Delete needless "IfModule" in apache configs
  lineinfile:
    path: /etc/httpd/conf.d/zabbix.conf
    regexp: IfModule
    state: absent
  become: yes

- name: Auto start zabbix-server and apache web server
  systemd:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  become: yes
  with_items:
    - zabbix-server
    - httpd

- name: |
    Zabbix installation completed.
    Visit http://Server-IP/zabbix/ and configure initial settings.
    Credentials for Zabbix Administrator login is Admin/zabbix.
  command: echo 
