# Install additional repositories
---
- name: roles/php-repo/tasks/repos.yml
  command: echo

- name: Check for access to the Internet
  wait_for: host=www.yahoo.co.jp port=80 timeout=5

- name: Check existence of RPM-GPG-KEY-EPEL-{{ _V }}
  stat:
    path: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ _V }}
  register: epel_key

- name: Import rpm-gpg key for epel
  rpm_key:
    key: http://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ _V }}
  become: yes
  when: epel_key.stat.exists == false

- name: Install additional repositories for CentOS {{ _V }}.x - epel
  yum_repository:
    name: epel-release
    description: Extra Packages for Enterprise Linux {{ _V }} - $basearch
    mirrorlist: "https://mirrors.fedoraproject.org/metalink?repo=epel-{{ _V }}&arch=$basearch"
    failovermethod: priority
    enabled: yes
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ _V }}
    gpgcheck: yes
  become: yes

- name: Install additional repositories for CentOS {{ _V }}.x - {{ PHP_REPO }}
  yum:
    name: "{{ PHP_REPO_PKG }}"
  become: yes
  when: PHP_REPO == 'remi72'

- name: Install PHP Repository for CentOS {{ _V }}.x
  yum:
    name: "{{ PHP_REPO_PKG }}"
    validate_certs: no
  become: yes
