#!/bin/bash
#
# A helper script to try pgpool_setup
# Usage:
#   source THIS_FILE
#   /path/to/pgpool_setup -s
#
export PGPOOL_INSTALL_DIR=/usr/pgpool-{{ PG_VERSION }}
export PGPOOLDIR=/etc/pgpool-II-{{ PG_VERSION }}
export PGBIN=/usr/pgsql-{{ PG_VERSION }}/bin
export PGLIB=/usr/pgsql-{{ PG_VERSION }}/lib
# If run as normal user, this will fail cause by permission denied.
# export PGSOCKET_DIR=/var/run/postgresql
export PGSOCKET_DIR=/tmp
export PGHOST=/tmp
env|grep PG|grep -v LS_
# /usr/pgpool-{{ PG_VERSION }}/bin/pgpool_setup -s
