#!/bin/bash
#
# A helper script to try pgpool_setup
# Usage:
#   source THIS_FILE
#   /path/to/pgpool_setup -s
#
export PGPOOL_INSTALL_DIR=/usr/pgpool-10
export PGPOOLDIR=/etc/pgpool-II-10
export PGBIN=/usr/pgsql-10/bin
export PGLIB=/usr/pgsql-10/lib
# If run as normal user, this will fail cause by permission denied.
# export PGSOCKET_DIR=/var/run/postgresql
export PGSOCKET_DIR=/tmp
export PGHOST=/tmp
env|grep PG|grep -v LS_
# /usr/pgpool-10/bin/pgpool_setup -s
